/// Detects if a commit was AI-authored based on commit message patterns.
/// Supports: Claude Code, Cursor, Aider, Codex CLI, GitHub Copilot, Gemini CLI.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AiTool {
    ClaudeCode,
    Cursor,
    Aider,
    CodexCli,
    GithubCopilot,
    GeminiCli,
    Other(String),
    Human,
}

impl std::fmt::Display for AiTool {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AiTool::ClaudeCode => write!(f, "Claude Code"),
            AiTool::Cursor => write!(f, "Cursor"),
            AiTool::Aider => write!(f, "Aider"),
            AiTool::CodexCli => write!(f, "Codex CLI"),
            AiTool::GithubCopilot => write!(f, "GitHub Copilot"),
            AiTool::GeminiCli => write!(f, "Gemini CLI"),
            AiTool::Other(name) => write!(f, "{}", name),
            AiTool::Human => write!(f, "Human"),
        }
    }
}

/// Analyze a commit message and return which AI tool authored it (if any).
pub fn detect_ai_tool(commit_message: &str) -> AiTool {
    let msg = commit_message.to_lowercase();

    // Claude Code patterns
    if msg.contains("co-authored-by: claude")
        || msg.contains("noreply@anthropic.com")
        || msg.contains("generated with claude code")
    {
        return AiTool::ClaudeCode;
    }

    // Cursor patterns
    if msg.contains("co-authored-by: cursor") {
        return AiTool::Cursor;
    }

    // Aider patterns
    if msg.contains("co-authored-by: aider")
        || msg.contains("noreply@aider.chat")
        || msg.contains("aider: ")
    {
        return AiTool::Aider;
    }

    // Codex CLI patterns
    if msg.contains("co-authored-by: codex")
        || msg.contains("generated by codex")
        || msg.contains("codex-cli")
    {
        return AiTool::CodexCli;
    }

    // GitHub Copilot patterns
    if msg.contains("co-authored-by: copilot")
        || (msg.contains("noreply@github.com") && msg.contains("copilot"))
        || msg.contains("github-copilot")
    {
        return AiTool::GithubCopilot;
    }

    // Gemini CLI patterns
    if msg.contains("co-authored-by: gemini")
        || msg.contains("noreply@google.com") && msg.contains("gemini")
    {
        return AiTool::GeminiCli;
    }

    AiTool::Human
}

#[cfg(test)]
mod tests {
    use super::*;

    // ── Claude Code ──

    #[test]
    fn detects_claude_code_co_authored() {
        let msg = "feat: add login page\n\nCo-Authored-By: Claude <noreply@anthropic.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::ClaudeCode);
    }

    #[test]
    fn detects_claude_code_opus() {
        let msg =
            "fix: resolve auth bug\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::ClaudeCode);
    }

    #[test]
    fn detects_claude_code_generated_footer() {
        let msg = "refactor: clean up utils\n\nGenerated with Claude Code";
        assert_eq!(detect_ai_tool(msg), AiTool::ClaudeCode);
    }

    // ── Cursor ──

    #[test]
    fn detects_cursor() {
        let msg = "feat: add dark mode\n\nCo-authored-by: Cursor";
        assert_eq!(detect_ai_tool(msg), AiTool::Cursor);
    }

    // ── Aider ──

    #[test]
    fn detects_aider_co_authored() {
        let msg =
            "feat: implement auth\n\nCo-authored-by: aider (claude-3.5-sonnet) <noreply@aider.chat>";
        assert_eq!(detect_ai_tool(msg), AiTool::Aider);
    }

    #[test]
    fn detects_aider_prefix() {
        let msg = "aider: fix: resolve login bug";
        assert_eq!(detect_ai_tool(msg), AiTool::Aider);
    }

    // ── Codex CLI ──

    #[test]
    fn detects_codex_co_authored() {
        let msg = "feat: add search\n\nCo-authored-by: Codex <noreply@openai.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::CodexCli);
    }

    #[test]
    fn detects_codex_generated() {
        let msg = "refactor: simplify api\n\nGenerated by Codex";
        assert_eq!(detect_ai_tool(msg), AiTool::CodexCli);
    }

    // ── GitHub Copilot ──

    #[test]
    fn detects_copilot() {
        let msg = "feat: add search\n\nCo-authored-by: copilot <noreply@github.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::GithubCopilot);
    }

    // ── Gemini CLI ──

    #[test]
    fn detects_gemini() {
        let msg = "feat: add caching\n\nCo-authored-by: Gemini <noreply@google.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::GeminiCli);
    }

    // ── Human ──

    #[test]
    fn detects_human_commit() {
        let msg = "fix: typo in readme";
        assert_eq!(detect_ai_tool(msg), AiTool::Human);
    }
}
