/// Detects if a commit was AI-authored based on commit message patterns.
/// Focused on Claude Code, with experimental support for other tools.

#[derive(Debug, Clone, PartialEq, Eq, Hash)]
pub enum AiTool {
    ClaudeCode,
    GithubCopilot,
    CodexCli,
    Other(String),
    Human,
}

impl std::fmt::Display for AiTool {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            AiTool::ClaudeCode => write!(f, "Claude Code"),
            AiTool::GithubCopilot => write!(f, "GitHub Copilot"),
            AiTool::CodexCli => write!(f, "Codex CLI"),
            AiTool::Other(name) => write!(f, "{}", name),
            AiTool::Human => write!(f, "Human"),
        }
    }
}

/// Analyze a commit message and return which AI tool authored it (if any).
pub fn detect_ai_tool(commit_message: &str) -> AiTool {
    let msg = commit_message.to_lowercase();

    // Claude Code patterns
    if msg.contains("co-authored-by: claude")
        || msg.contains("noreply@anthropic.com")
        || msg.contains("generated with claude code")
    {
        return AiTool::ClaudeCode;
    }

    // GitHub Copilot patterns
    if msg.contains("co-authored-by: copilot")
        || (msg.contains("noreply@github.com") && msg.contains("copilot"))
        || msg.contains("github-copilot")
    {
        return AiTool::GithubCopilot;
    }

    // Codex CLI
    if msg.contains("generated by codex") || msg.contains("codex-cli") {
        return AiTool::CodexCli;
    }

    AiTool::Human
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_claude_code_co_authored() {
        let msg = "feat: add login page\n\nCo-Authored-By: Claude <noreply@anthropic.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::ClaudeCode);
    }

    #[test]
    fn detects_claude_code_opus() {
        let msg =
            "fix: resolve auth bug\n\nCo-Authored-By: Claude Opus 4.6 <noreply@anthropic.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::ClaudeCode);
    }

    #[test]
    fn detects_claude_code_generated_footer() {
        let msg = "refactor: clean up utils\n\nGenerated with Claude Code";
        assert_eq!(detect_ai_tool(msg), AiTool::ClaudeCode);
    }

    #[test]
    fn detects_human_commit() {
        let msg = "fix: typo in readme";
        assert_eq!(detect_ai_tool(msg), AiTool::Human);
    }

    #[test]
    fn detects_copilot() {
        let msg = "feat: add search\n\nCo-authored-by: copilot <noreply@github.com>";
        assert_eq!(detect_ai_tool(msg), AiTool::GithubCopilot);
    }
}
